// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: ubqwhgybbbnehlufwhem

class SupabaseConfig {
  static const String supabaseUrl = 'https://ubqwhgybbbnehlufwhem.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVicXdoZ3liYmJuZWhsdWZ3aGVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3NzY3MzIsImV4cCI6MjA4NDM1MjczMn0.L4Td-rkTqRJBCfE2Ok_zzC-JqV0GKVrNiDySgeaHX7s';
}
